# Generated by Django 5.0.14 on 2026-07-29 03:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('especialidad', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('biografia', models.TextField(blank=True, default='')),
                ('tarifa_hora', models.DecimalField(decimal_places=2, default=75.0, max_digits=10)),
                ('avatar_url', models.CharField(blank=True, default='assets/img/trainers/trainer-1.jpg', max_length=255)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_consultor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultor',
                'verbose_name_plural': 'Consultores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ClienteMentoreado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('empresa', models.CharField(max_length=150)),
                ('sector', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL)),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='Consultorias.consultor')),
            ],
            options={
                'verbose_name': 'Cliente Mentoreado',
                'verbose_name_plural': 'Clientes Mentoreados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('prioridad', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('progreso_porcentaje', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='Consultorias.clientementoreado')),
            ],
            options={
                'verbose_name': 'Objetivo / Hito',
                'verbose_name_plural': 'Objetivos / Hitos',
                'ordering': ['prioridad', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='entregables/')),
                ('enlace_externo', models.URLField(blank=True, default='')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('comentarios_consultor', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='Consultorias.clientementoreado')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='Consultorias.objetivo')),
            ],
            options={
                'verbose_name': 'Entregable',
                'verbose_name_plural': 'Entregables',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='SesionMentoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('INDIVIDUAL', 'Mentoría Individual'), ('GRUPAL', 'Mentoría Grupal')], default='INDIVIDUAL', max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('modalidad', models.CharField(choices=[('VIRTUAL', 'Virtual (Meet / Zoom)'), ('PRESENCIAL', 'Presencial')], default='VIRTUAL', max_length=20)),
                ('enlace_reunion', models.URLField(blank=True, default='')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20)),
                ('notas_sesion', models.TextField(blank=True, default='')),
                ('calificacion_nps', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('feedback_cliente', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_individuales', to='Consultorias.clientementoreado')),
                ('clientes_grupales', models.ManyToManyField(blank=True, related_name='sesiones_grupales', to='Consultorias.clientementoreado')),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='Consultorias.consultor')),
            ],
            options={
                'verbose_name': 'Sesión de Mentoría',
                'verbose_name_plural': 'Sesiones de Mentoría',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
