# Generated by Django 5.0.14 on 2026-07-29 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientementoreado',
            options={'verbose_name': 'Cliente Mentoreado', 'verbose_name_plural': 'Clientes Mentoreados'},
        ),
        migrations.AlterModelOptions(
            name='consultor',
            options={'verbose_name': 'Consultor', 'verbose_name_plural': 'Consultores'},
        ),
        migrations.AlterModelOptions(
            name='objetivo',
            options={'ordering': ['prioridad', 'id'], 'verbose_name': 'Objetivo', 'verbose_name_plural': 'Objetivos'},
        ),
        migrations.RemoveField(
            model_name='consultor',
            name='avatar_url',
        ),
        migrations.AlterField(
            model_name='clientementoreado',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultor',
            name='tarifa_hora',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consultor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entregable',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='sesionmentoria',
            name='modalidad',
            field=models.CharField(choices=[('VIRTUAL', 'Virtual'), ('PRESENCIAL', 'Presencial')], default='VIRTUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='sesionmentoria',
            name='tipo',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GRUPAL', 'Grupal')], default='INDIVIDUAL', max_length=20),
        ),
    ]
