# Generated by Django 5.0.14 on 2026-08-05 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultorias', '0002_alter_clientementoreado_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregable',
            name='enlace_externo',
        ),
        migrations.RemoveField(
            model_name='sesionmentoria',
            name='enlace_reunion',
        ),
    ]
